<?php

/**
 * @file
 * Contains functions for the Mmenu Region module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mmenu_region_form_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\block\BlockInterface $block */
  $block = $form_state->getFormObject()->getEntity();

  // Only show this for blocks in the mmenu region.
  if ($block->getRegion() != 'mmenu') {
    return;
  }

  // This will automatically be saved in the third party settings.
  $form['third_party_settings']['#tree'] = TRUE;
  $form['third_party_settings']['mmenu_region']['collapse'] = array(
    '#type' => 'checkbox',
    '#title' => t('Collapse this block onto a new mmenu panel.'),
    '#default_value' => $block->getThirdPartySetting('mmenu_region', 'collapse'),
  );
}

/**
 * Implements hook_page_bottom().
 */
function mmenu_region_page_bottom(array &$page_bottom) {
  $view_builder = \Drupal::entityTypeManager()
    ->getViewBuilder('block');

  $mmenu_blocks = [];
  foreach (_mmenu_region_get_blocks() as $key => $block) {
    if ($block->access('view')) {
      $mmenu_blocks[$key]['title'] = $block->label();
      $mmenu_blocks[$key]['content'] = $view_builder->view($block);
      $mmenu_blocks[$key]['collapsed'] = $block->getThirdPartySetting('mmenu_region', 'collapse');
    }
  }

  if (!empty($mmenu_blocks)) {
    $page_bottom['mmenu'] = [
      '#theme' => 'mmenu_region',
      '#blocks' => $mmenu_blocks,
      '#attached' => [
        'library' => [
          'mmenu_region/mmenu.cdn',
          'mmenu_region/mmenu_region',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_system_info_alter().
 */
function mmenu_region_system_info_alter(array &$info, \Drupal\Core\Extension\Extension $file, $type) {
  if ($type == 'theme') {
    $info['regions']['mmenu'] = 'Mmenu';
  }
}

/**
 * Implements hook_theme().
 */
function mmenu_region_theme($existing, $type, $theme, $path) {
  return [
    'mmenu_region' => [
      'variables' => [
        'blocks' => [],
      ],
    ],
  ];
}

/**
 * Preprocesses variables for the mmenu_region twig template.
 *
 * @param array $variables
 *   An array of variables to pass to the template.
 */
function template_preprocess_mmenu_region(&$variables) {
  foreach ($variables['blocks'] as $key => $block) {
    $id = 'mmenu-block-' . $key;
    $attributes = [
      'id' => $id,
    ];
    if (isset($block['collapsed']) && $block['collapsed']) {
      $variables['blocks'][$key]['title_href'] = '#' . $id;
      $attributes['class'] = 'Panel';
    }
    $variables['blocks'][$key]['attributes'] = new \Drupal\Core\Template\Attribute($attributes);
  }
}

/**
 * Loads Mmenu region blocks from storage.
 *
 * @return \Drupal\block\BlockInterface[]
 *   The blocks assigned to the Mmenu region.
 */
function _mmenu_region_get_blocks() {
  static $blocks = NULL;
  if ($blocks === NULL) {
    /** @var \Drupal\block\BlockInterface[] $blocks */
    $blocks = \Drupal::entityTypeManager()
      ->getStorage('block')
      ->loadByProperties(['region' => 'mmenu']);
    uasort($blocks, 'Drupal\block\Entity\Block::sort');
  }
  return $blocks;
}
